<?php
$this->headTitle('View Group');

?>

<h1>View Group</h1>

<p>
    <a class="btn btn-default" href="
        <?= $this->url('group', ['action'=>'edit', 'id' => $group->getId()]); ?>">
        Update
    </a>
    <a class="btn btn-default" href="
        <?= $this->url('group', ['action'=>'delete', 'id' => $group->getId()]); ?>">
        Delete
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>Group ID:</th>
                <td><?= $this->escapeHtml($group->getId()) ?></th>
            </tr>
            <tr>
                <th>Name:</th>
                <td><?= $this->escapeHtml($group->getName()) ?></th>
            </tr>
        </table>
    </div>
</div>
