<?php
$this->headTitle('View Consumer');

?>

<h1>View Consumer</h1>

<p>
    <a class="btn btn-default" href="
        <?= $this->url('consumer', ['action'=>'edit', 'id' => $consumer->getId()]); ?>">
        Update
    </a>
    <a class="btn btn-default" href="
        <?= $this->url('consumer', ['action'=>'delete', 'id' => $consumer->getId()]); ?>">
        Delete
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>Consumer ID:</th>
                <td><?= $this->escapeHtml($consumer->getId()) ?></th>
            </tr>
            <tr>
                <th>Avatar:</th>
                <td><?php
                    if ($consumer->getAvatarFileName()) {
                        ?><img src="<?=$this->url('images', ['width' => 300, 'file' => $consumer->getAvatarFileName()]) ?>"/><?php
                    } else {
                        ?>Not set<?php
                    }
                ?></td>
            </tr>
            <tr>
                <th>Login:</th>
                <td><?= $this->escapeHtml($consumer->getLogin()) ?></td>
            </tr>
            <tr>
                <th>Password:</th>
                <td><?= $this->escapeHtml($consumer->getPassword()) ?></td>
            </tr>
            <tr>
                <th>Group:</th>
                <td><?= $this->escapeHtml($consumer->getGroup()->getName()) ?></td>
            </tr>

            <tr>
                <th>Email:</th>
                <td><?= $this->escapeHtml($consumer->getEmail()) ?></td>
            </tr>
            <tr>
                <th>ExpirationDateTime:</th>
                <td><?= $this->escapeHtml($consumer->getExpirationDateTime()) ?></td>
            </tr>


        </table>
    </div>
</div>
