<?php
$this->headTitle('Login');

$form = $this->form;
$form->get('login')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Enter post login here',
    ]);
$form->get('password')->setAttributes([
        'class'=>'form-control',
        'placeholder'=>'Type password here',
    ]);
$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);
$form->get('submit')->setValue('Login');
$form->prepare();
?>

<h1>Login</h1>

<p>
    Please fill out the following form and click the *Login* button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('login')); ?>
            <?= $this->formElement($form->get('login')); ?>
            <?= $this->formElementErrors($form->get('login')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>